#!/bin/bash
yum update -y
yum install -y httpd
systemctl start httpd
systemctl enable httpd
echo '<html><body style="background-color:green; color:white"><h1>🟦 VERSION 1 (GREEN)</h1></body></html>' > /var/www/html/index.html
